### ISSUE TITLE
[feature request] option page

### ISSUE THREAD

**Issue by tubbadu** [igorlogius/forward-download#3]
an option page to set executable path and other things

**Comment by igorlogius** [comment]
AFAIK, this can not really be done ... since the 
 execution path to the native-messaging application can not be dynamically changed 

Of course ... one could use a generic exec handler script  `eval XYZ`  which takes the intput from the option page ...
but this ... feels like it could be a huge security risk.  It would essentially allow the addon do execute anything on the System. 
Not sure if i am comfortable with this.

But i guess ... creating the generic exec handler ... would hurt.
